Feature/crud for news
MrFurion/NewsLogicServer pull request #2
Opened 2024-12-16 13:15 UTC by MrFurion

2024-12-16 17:26 UTC, YuliyaDzemidovich requested changes

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on api/src/main/java/by/clevertec/ApiLogicServerApplicetion.java
> +public class ApiLogicServerApplicetion {
опечатка Application

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on api/src/main/java/by/clevertec/controllers/NewsController.java
> +@RequestMapping("/app/news")
/app можно убрать или, если очень хочется, добавить в проперти как context path - так тебе не нужно будет добавлять этот кусочек пути в каждый контроллер

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on api/src/main/java/by/clevertec/controllers/NewsController.java
> +    public ResponseEntity<News> findNews(@PathVariable UUID id) {
fyi здесь можно оставить как есть - UUID входящим параметром
Или же принимать String и конвертировать вручную в UUID - в таком случае будет больше контроля над тем, что вернуть клиенту в случае невалидного UUID (нужна ли какая-то красивая ошибка)

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on core/src/main/java/by/clevertec/exception/GlobalExceptionHandler.java
> +    public static final String DESCRIPTION = "description";
если константа нигде больше не используется, то лучше держать модификатор доступа как можно более узким, т.е. private
Если же используется, то лучше выносить константы в отдельный класс констант

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on core/src/main/java/by/clevertec/models/Comment.java
> +    private UUID id;
А почему ты решил взять UUID в качестве primary key? Если это не строгое требование, то я бы предпочла sequential ID (можно с небольшим шагом, чтобы не было видно по ID сколько всего в базе записей). В best practices пишут что у UUID хуже с потреблением памяти, сортировкой (если нужно) и производительностью:
[https://www.baeldung.com/uuid-vs-sequential-id-as-primary-key](url)

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on core/src/main/java/by/clevertec/models/Comment.java
> +    private LocalDate time;
почему выбрал LocalDate?
Во-первых, там нету компонента time, то есть это просто дата без времени.
Во-вторых, там нету таймзоны - то есть это просто время на часах. Если нет требования к поддержке таймзон, я бы все равно выбрала UTC как серверное время (в приложухе и БД), с заделом на будущее (добавить таймзоны позже если понадобится)

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on core/src/main/java/by/clevertec/services/impl/NewsServiceImpl.java
> +@Transactional(readOnly=true)
вроде бы нет импакта на производительность если выполняются create/update/delete, а ты советуешь jpa использовать read only транзакции - но я бы перепроверила этот момент

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on core/src/main/java/by/clevertec/services/impl/NewsServiceImpl.java
> +
пустые места оставлять нехорошо - хотя бы todo написать и какой-то мог
например логгер с "мок создания объекта". Кроме того, тебе скорее всего понадобится созданный объект вернуть обратно, или хотя бы его id

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on docker-compose.yml
> +      POSTGRES_PASSWORD: admin
паролей никаких в пропертях быть не должно - все через системные переменные/другую подстановку должно передаваться
Возможно, после разделения на спринг профили, возможно будет и проперти файлы разделить на секреты и обычные проперти (секреты вместе с основным кодом не заливаются в репо - по крайней мере прод так точно)

2024-12-16 17:26 UTC, YuliyaDzemidovich commented on src/main/resources/db/changelog/V1__Default_Models.sql
> +                        username VARCHAR(25) not null unique,
username unique - значит пользователь может оставить только один коммент за всё время?

2024-12-17 13:09 UTC, MrFurion commented on api/src/main/java/by/clevertec/ApiLogicServerApplicetion.java
> +public class ApiLogicServerApplicetion {
corrected

2024-12-17 13:10 UTC, MrFurion commented on api/src/main/java/by/clevertec/controllers/NewsController.java
> +@RequestMapping("/app/news")
Убрал. При конденге пробовал разные пути забыл удалить.

2024-12-17 13:16 UTC, MrFurion commented on api/src/main/java/by/clevertec/controllers/NewsController.java
> +    public ResponseEntity<News> findNews(@PathVariable UUID id) {
я сделал костюмную ошибку и хандлером отлавливаю ее. 
![image](https://github.com/user-attachments/assets/0cc75069-1fa5-4785-abf4-0194ffcc0197)

2024-12-17 13:18 UTC, MrFurion commented on core/src/main/java/by/clevertec/exception/GlobalExceptionHandler.java
> +    public static final String DESCRIPTION = "description";
Сделал приватной.

2024-12-17 13:22 UTC, MrFurion commented on core/src/main/java/by/clevertec/models/Comment.java
> +    private UUID id;
Я не разу не работал с UUID хочу попробовать здесь. UUID так же гарантирует уникальность ни в одной бд. Плюс Тз направлено на создание микро сервисов, а UUID рекомендуется для использования в них. Так как совместимость бд и безопасность.

2024-12-17 13:57 UTC, MrFurion commented on core/src/main/java/by/clevertec/models/Comment.java
> +    private LocalDate time;
Мало опыта. Исправил и пробую с Instant.

2024-12-17 14:15 UTC, MrFurion commented on docker-compose.yml
> +      POSTGRES_PASSWORD: admin
Это я помню ты объясняла. Это еще сделаю. Ну плюс это тестовое задание.

2024-12-17 14:19 UTC, MrFurion commented on src/main/resources/db/changelog/V1__Default_Models.sql
> +                        username VARCHAR(25) not null unique,
Я почему-то подумал что это поможет избавиться от спама одним юзером как это делается в дедосе но что-то намудрил. Исправил.

2024-12-17 14:24 UTC, MrFurion commented on core/src/main/java/by/clevertec/services/impl/NewsServiceImpl.java
> +@Transactional(readOnly=true)
Насколько знаю это хороший тон задавать эту аннотацию. Плюс будут добавлены по тз еще несколько методов по чтению. Так же помогает избегать случайных изменений.

2024-12-18 11:26 UTC, MrFurion commented on core/src/main/java/by/clevertec/services/impl/NewsServiceImpl.java
> +
corected

2024-12-18 12:44 UTC, merged